on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2.3.4

      - name: Run a build script
        run: .github/workflows/build.ps1

      - name: Attach build artifacts to current job
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Build results
          path: Build/*.zip

      - name: Create a release draft if current commit is tagged
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: Build/*.zip
          fail_on_unmatched_files: true
  test_on_linux:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the repo
          uses: actions/checkout@v2.3.4
        - name: Run tests
          run: python src/test.py -v
